Re Order future added
kavilashTech/quicklabv2 pull request #44
Opened 2023-04-27 07:35 UTC by surya-ultiweb

2023-04-27 07:51 UTC, priya-ultiweb requested changes

2023-04-27 07:51 UTC, priya-ultiweb commented on app/Http/Controllers/PurchaseHistoryController.php
> +		$insertcart['shipping_cost'] = 0;
Why is shipping cost 0 ? Can you pls confirm if we cannot take shipping cost from DB ?

2023-04-27 07:51 UTC, priya-ultiweb commented on resources/views/frontend/user/order_details_customer.blade.php
> +                                <th data-breakpoints="md" class="text-right">{{ translate('Re Order') }}</th>
We spoke about having one column for both Return and Re-order - right - Can you pls confirm we can achieve that ?

2023-04-27 07:58 UTC, surya-ultiweb commented on app/Http/Controllers/PurchaseHistoryController.php
> +		$insertcart['shipping_cost'] = 0;
Shipping cost will be calculated while checkout the product

2023-04-27 07:59 UTC, surya-ultiweb commented on resources/views/frontend/user/order_details_customer.blade.php
> +                                <th data-breakpoints="md" class="text-right">{{ translate('Re Order') }}</th>
i tried that once i put this in same column other buttons it's not appeared

2023-04-27 08:14 UTC, surya-ultiweb commented on resources/views/frontend/user/order_details_customer.blade.php
> +                                <th data-breakpoints="md" class="text-right">{{ translate('Re Order') }}</th>
> We spoke about having one column for both Return and Re-order - right - Can you pls confirm we can achieve that ?

changes done and pushed.

2023-05-01 10:19 UTC, priya-ultiweb approved these changes

2023-05-01 10:19 UTC, priya-ultiweb approved these changes

2023-05-01 10:29 UTC, merged